use_frameworks!

target 'ThrymrsPaymentsKit_Example' do
  pod 'ThrymrsPaymentsKit', :path => '../'

  target 'ThrymrsPaymentsKit_Tests' do
    inherit! :search_paths

    
  end
  
  pod 'OpenSSL'
  
  pod 'TFHpple'
  
  pod 'AFNetworking', '~> 2.3'
end
